### ISSUE TITLE
System.NullReferenceException is thrown during publishing page of type which has no template

### ISSUE THREAD

**Issue by PiotrDela** [fortedigital/EPiAutoAlias#5]
`System.NullReferenceException: Object reference not set to an instance of an object.
   at Forte.UrlRedirects.UrlRewritePlugin.StringExtensions.NormalizePath(String str)
   at Forte.UrlRedirects.UrlRewritePlugin.RedirectHelper.AddRedirectsToDDS(PageData pageData, String oldUrl)
   at Forte.UrlRedirects.UrlRewritePlugin.UrlRewriteModule.EventsPublishedContent(Object sender, ContentEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at EPiServer.Core.Internal.DefaultContentEvents.RaiseContentEvent(String key, ContentEventArgs eventArgs)
   at EPiServer.Core.Internal.DefaultContentRepository.RaisePostSaveEvents(SaveContentEventArgs eventArgs, StatusTransition transition, Boolean isNew, Boolean isNewLanguageBranch)
   at EPiServer.Core.Internal.DefaultContentRepository.Save(IContent content, SaveAction action, AccessLevel access)
   at EPiServer.Cms.Shell.Service.Internal.ContentService.Save(IContent content, SaveAction saveAction, AccessLevel accessLevel)
   at EPiServer.Cms.Shell.Service.Internal.ContentService.Save(IContent content, SaveAction saveAction)
   at EPiServer.Cms.Shell.Workspace.Committers.Internal.ContentDataCommitter.Commit(EditContentData change, CommitArguments argument)`

**Comment by kpkozak** [comment]
probably fixed by 8f5849dc2c65c845ce632b42ff5e008885960150? Could be closed?
@PiotrDela

**Comment by PiotrDela** [comment]
True, I'm closing
